export const the_robbery_prologue = {
  slug: "the-robbery",
  title: "The-Robbery",
  previewStart: 0,
  previewLength: 3,
  previewCharacters: 780,
  paragraphs: [
    `Prologue`,
    `The Defendant of Nothing`,
    `The Charge`,
    `There are men who lose love and become poets. Others become drunkards. Some become philosophers, though that last category is often crowded with cowards who own excellent vocabularies.`,
    `And then there was the man who became a defendant.`,
    `Not in any court the city recognized, though Brooklyn has always been generous with its tribunals. There are courts in bodegas, in barbershops, in the silence after an unanswered message, and in the pause before someone says, "I’m fine," without meaning it. But his trial took place somewhere more private and more severe: behind the sternum, beneath the ribs, in that dim jurisdiction where memory serves as clerk, grief as bailiff, and the heart—if it has not fled the premises entirely—appears as a hostile witness.`,
    `The charge was peculiar. He stood accused of defending empty space.`,
    `At first glance, the accusation seemed absurd. Men have defended less: borders, reputations, parking spaces, opinions borrowed secondhand and worn like tailored suits. A man may defend a lie for decades and be called principled. He may defend cruelty and be praised for strength. He may defend silence and be called dignified. But to defend empty space was something else. It required imagination. It required discipline. Above all, it required injury.`,
    `The Injury`,
    `He had been injured. That must be said plainly, because people can be merciless when confronted with another person’s armor. They admire the shine and condemn the weight. They ask why the guarded do not simply open, with the casual innocence of people who have never had their inner rooms ransacked.`,
    `He had loved—not spectacularly, not in the manner of operas or rain-soaked platforms, but earnestly, which is often worse. Spectacle announces its danger. Earnestness slips in quietly, removes its shoes at the door, learns where the glasses are kept, and by the time it leaves, it has rearranged the furniture of the soul.`,
    `The first woman did not destroy him. No one ever does, though the abandoned like to grant their former lovers mythic powers. She simply left. She took her books, her blue scarf, and the little brass lamp she insisted made the apartment warmer, then departed with the clean efficiency of someone who had rehearsed mercy in advance. Afterward, the apartment seemed larger in all the wrong ways.`,
    `The second woman was kinder, which made her more dangerous. Cruelty is easy to hate; kindness, when it leaves, creates theological problems. If good people can leave, then goodness is no guarantee. If tenderness can vanish, then tenderness is no shelter. If love can look you in the face and still choose absence, perhaps love was never the opposite of abandonment. Perhaps it was only abandonment with better lighting.`,
    `By the third, he had begun keeping records—not on paper, because paper would have made him ridiculous, and he was not yet ready for that. He kept the ledger internally: a laugh lost here, a softness there, a willingness to believe, a spontaneous phone call, a Sunday morning unburdened by suspicion. To anyone watching from outside, these were small losses. Inside him, they accrued with the precision of debt.`,
    `People speak of heartbreak as though the heart breaks once. This is optimistic. The heart is not glass. It is property: entered, occupied, damaged, appraised, renovated, condemned, and occasionally sold below value to someone with beautiful eyes and unreliable intentions.`,
    `The Fortress`,
    `So the man did what injured men have done since the first cave became a home: he fortified.`,
    `He installed locks everywhere. Not merely on his door, though there were those too—three deadbolts, a chain, a bar angled beneath the knob with the grim practicality of siegecraft. He installed locks in his speech, in his calendar, in his laughter. He learned to pause before enthusiasm, to ration disclosure, and to answer invitations with "maybe" while meaning "no." In time, he became fluent in the language of polite disappearance.`,
    `And he called this wisdom.`,
    `There is no arrogance more convincing than the arrogance of the wounded. They have evidence. They have dates. They have receipts. They can point to the exact season when the weather changed inside them. They can tell you who failed to call, who chose someone else, who promised without intending, and who entered gently only to leave carrying something unnamed.`,
    `"I was robbed," he would later say. And who could deny it? Something had been taken. That much was true.`,
    `But the problem with being robbed is that afterward one becomes a student of doors. The world begins to divide itself into two kinds of people: those who have stolen and those waiting for the chance. The wounded imagination becomes an architect of prisons. It drafts blueprints in the language of safety and builds walls so intelligently that even the prisoner applauds the design.`,
    `Years passed. His friends called him private. His coworkers called him disciplined. Women called him difficult, then interesting, then unavailable, and eventually stopped calling him anything at all. He mistook their retreat for proof of his theory. See, he thought, how easily people leave when there is nothing left to take.`,
    `The Companion`,
    `But something remained with him. At first, he did not know its name. It sat politely at the edge of his bed after the first departure. After the second, it moved to the chair by the window. After the third, it began making itself useful: holding the room together, keeping the evenings quiet, asking nothing of him. It did not accuse, did not demand, and did not arrive late smelling of someone else’s future.`,
    `Eventually, he named it Solitude. It was a flattering name, and like most flattering names, it was not entirely honest. Its true name was Emptiness.`,
    `Emptiness is much maligned by those who have never needed it. They imagine it as a void, a punishment, or a failure of social appetite. They do not understand its manners. Emptiness can be exquisitely well behaved. It does not interrupt. It does not betray confidences. It does not forget anniversaries because it never asked to celebrate them. It sits beside you in restaurants and never reaches across the table to wound you. In many respects, it is the perfect companion for anyone who has come to distrust the living.`,
    `And so the man grew fond of it. This is where the tragedy begins—not when love leaves, but when absence becomes beloved.`,
    `He came to prefer the clean room, the unshared bed, the evening unmarred by another person’s weather. He began to see compromise as contamination and longing as an early symptom of relapse. On certain nights, when Brooklyn pressed its noise against his windows—the sirens, the laughter, the arguments rising from the sidewalk like steam—he would turn the locks one by one and feel an almost sacred relief.`,
    `•	No one could enter.`,
    `•	No one could take.`,
    `•	No one could leave.`,
    `This, he believed, was freedom.`,
    `But freedom, like love, is often recognized too late by those who traded it for control. Control is punctual. Control is neat. Control does not embarrass you in public or leave you waiting by the phone. Control lets you sleep. It also lets you grow old without witnesses.`,
    `The Trial`,
    `By the time the court convened, he had long since forgotten that he had built it himself. The judge wore the faces of women he had loved and blamed. The prosecutor spoke in his own voice, sharpened by conscience. The gallery was filled with the selves he had abandoned: the trusting one, the foolish one, the generous one, the one who once believed a closed door was merely a door and not a philosophy.`,
    `The bailiff called the room to order. The man rose.`,
    `He was prepared. Of course he was prepared. The wounded are always prepared. They have rehearsed their testimony in showers, in traffic, and in the half-sleep before dawn. They know their opening statement. They know the evidence. They know exactly where to place the blame so that pain appears logical.`,
    `"How do you plead?" the court asked.`,
    `He lifted his chin. "Not guilty," he said. "I was robbed."`,
    `For a moment, even the silence seemed to agree.`,
    `But somewhere inside that silence, Emptiness smiled—not cruelly, not triumphantly, but with the patience of something that had waited years to be mistaken for salvation.`,
    `The trial had begun.`
  ],
};
