export const the_other_half_prologue = {
  slug: "the-other-half",
  title: "The-Other-Half",
  previewStart: 0,
  previewLength: 3,
  previewCharacters: 780,
  paragraphs: [
    `Prologue`,
    `The Cost of Clarity`,
    `Once, Love Was a Mystery`,
    `There was a time when love was considered a mystery.`,
    `A troublesome one, certainly—a source of heartbreak, jealousy, betrayal, longing, foolishness, and songs that outlasted the people who wrote them. Entire civilizations stumbled through it. Religions sanctified it. Philosophers dissected it. Poets surrendered to it.`,
    `And yet, for all its chaos, humanity tolerated the inconvenience, because hidden inside the confusion was a peculiar belief: the things most worth having could not be separated from the risks required to obtain them.`,
    `The Urge to Optimize`,
    `Then, as humanity often does, we improved the problem.`,
    `•	We measured attraction.`,
    `•	We mapped desire.`,
    `•	We cataloged compatibility.`,
    `•	We quantified attachment, stability, temperament, fertility, parental investment, conflict resolution, emotional resilience, and long-term outcomes.`,
    `At first, the discoveries felt liberating, and many of them were. People learned things about themselves that previous generations could only guess at. Relationships became more transparent. Expectations grew clearer. Old hypocrisies began to collapse beneath the weight of data.`,
    `But progress has a habit few recognize until it is too late: once something becomes understandable, the temptation to optimize it soon follows. And once a thing can be optimized, someone eventually asks whether it should be.`,
    `A Revolution by Consensus`,
    `The world you are about to enter was born from that question—not through tyranny, conquest, or force, but through consensus. The most durable revolutions rarely arrive wearing boots. They arrive wearing solutions.`,
    `The Problem They Thought They Solved`,
    `The architects of this new society observed an uncomfortable truth: human beings did not always seek the same qualities in the people they desired and the people they trusted. The qualities that ignited longing were not always the ones that sustained households. The traits that inspired passion were not always the traits that nurtured children. The people most desired were not necessarily the people most relied upon.`,
    `For centuries, humanity treated this contradiction as an unfortunate complication. The architects treated it as an engineering problem—and engineers, by nature, dislike inefficiency.`,
    `What followed was hailed as one of civilization’s greatest achievements:`,
    `•	Conflict diminished.`,
    `•	Families stabilized.`,
    `•	Children flourished.`,
    `•	Economic outcomes improved.`,
    `•	Social trust increased.`,
    `The numbers were extraordinary—perhaps even undeniable. The system worked. That is what makes this story dangerous.`,
    `Why Success Is More Dangerous Than Failure`,
    `Stories about failed systems are easy. Their flaws reveal themselves immediately. Their victims cry out. Their consequences arrive loudly.`,
    `Stories about successful systems are far more difficult—especially when the success is real, when the people benefiting are not lying, and when the system delivers exactly what it promised. Those are the stories worth fearing.`,
    `A successful system can survive questions that would destroy a failed one. It can point to:`,
    `•	Results`,
    `•	Statistics`,
    `•	Prosperity`,
    `•	Healthier children`,
    `•	Longer marriages`,
    `•	Reduced suffering`,
    `And then it can ask a devastating question in return: What exactly would you have us abandon?`,
    `The Shadow at the Edge of the Equation`,
    `The world of The Other Half has an answer for nearly everything: an explanation for every tradeoff, a justification for every compromise, a metric for every outcome. It understands human desire so thoroughly that desire itself becomes predictable.`,
    `And yet there remains a shadow at the edge of the equation: a discomfort, a silence, a feeling that something essential has been solved out of existence.`,
    `Perhaps the problem is this: love was never merely a function. It was never solely reproductive, emotional, practical, or romantic. Its peculiar power came from refusing to remain in any category for long.`,
    `•	Irrational and necessary`,
    `•	Selfish and sacrificial`,
    `•	Biological and transcendent`,
    `•	Predictable and miraculous`,
    `It belonged nowhere because it belonged everywhere.`,
    `What Was Gained—and What Was Lost`,
    `The architects sought clarity. What they created was separation. Desire was placed in one room, commitment in another, parenthood in another, security in another. The pieces functioned beautifully. The question that remained was whether the whole survived.`,
    `This Is Not a Story About Villains`,
    `The architects are not villains. The mothers are not villains. The fathers are not villains. The desirable men are not villains. The reliable men are not villains. Even the system itself is not a villain.`,
    `The true antagonist is more elusive: the possibility that human beings can become so skilled at solving problems that they eventually solve away the conditions that made them human.`,
    `Every generation inherits a different illusion. Some believe freedom is the highest virtue. Others believe equality is. Others still believe order is. The generation that built this world believed optimization was. And optimization, like every god before it, demanded sacrifice.`,
    `The difficulty lies in recognizing what was placed upon the altar. Perhaps nothing was lost. Perhaps humanity merely outgrew an inefficient tradition. Perhaps the architects were right all along. Or perhaps some truths become visible only after the problem has been solved.`,
    `That is the question at the heart of this world: not whether the system works—it does; not whether people are happier—many are; not whether children thrive—they do.`,
    `The question is simpler, and therefore far more dangerous.`,
    `If you divide love into its component parts and optimize each one separately, what becomes of the thing that once existed between them?`
  ],
};
