export const the_mirror_doesnt_work_prologue = {
  slug: "the-mirror-doesnt-work",
  title: "the-mirror-doesnt-work",
  paragraphs: [
    `# Prologue`,
    `## The Gaze We Inherited`,
    `When I was young, I believed the cruelest thing a person could suffer was invisibility.`,
    `I believed this because I had watched people spend entire lives trying not to disappear.`,
    `Some chased wealth.`,
    `Some chased beauty.`,
    `Some chased power.`,
    `Most chased approval.`,
    `They wanted to be noticed. Remembered. Confirmed.`,
    `To exist, it seemed, required witnesses.`,
    `And so they stood before mirrors.`,
    `Not the glass kind.`,
    `Not at first.`,
    `The mirrors I speak of were older than technology and far more patient.`,
    `They lived in the eyes of parents.`,
    `In the expectations of teachers.`,
    `In the approval of lovers.`,
    `In the laughter of strangers.`,
    `In the silence of those who looked away.`,
    `Every human being carried one.`,
    `Every society built entire institutions around them.`,
    `And every generation inherited them from the one before.`,
    `Long before the machines arrived, we had already learned to ask a question that would shape the rest of our lives:`,
    `*What do they see when they look at me?*`,
    `It is a small question.`,
    `An innocent question.`,
    `A question so common that most people never notice they are asking it.`,
    `Yet entire civilizations have been built upon its answer.`,
    `Wars have been fought because of it.`,
    `Empires have justified themselves through it.`,
    `Families have fractured beneath its weight.`,
    `Children have abandoned themselves in pursuit of it.`,
    `And some have died never realizing they were still asking it.`,
    `What do they see?`,
    `What do they see?`,
    `What do they see?`,
    `The question became so familiar that eventually we mistook it for identity itself.`,
    `Then the mirrors learned to speak.`,
    `Technology always arrives late to human folly.`,
    `It rarely invents our mistakes.`,
    `It merely industrializes them.`,
    `The machines that came later"”the systems, the rankings, the calibrations, the endless measurements"”were not revolutionary.`,
    `They were inevitable.`,
    `We had already spent centuries teaching one another that worth could be observed, quantified, and distributed.`,
    `The machines simply automated the process.`,
    `And because they were machines, we trusted them more than ourselves.`,
    `A machine, after all, has no prejudice.`,
    `A machine has no envy.`,
    `A machine has no resentment.`,
    `Or so we told ourselves.`,
    `The machine merely reflected.`,
    `The machine merely measured.`,
    `The machine merely revealed what was already there.`,
    `That was the lie.`,
    `Not the first lie.`,
    `Not the largest lie.`,
    `But the one that mattered.`,
    `Because once people believe a reflection is reality, they will surrender almost anything to improve it.`,
    `Their language.`,
    `Their history.`,
    `Their memories.`,
    `Their children.`,
    `The machine did not need chains.`,
    `It had mirrors.`,
    `And the mirrors worked beautifully.`,
    `At least in the beginning.`,
    `They told people who they were.`,
    `People were grateful.`,
    `The mirrors told them who mattered.`,
    `People applauded.`,
    `The mirrors told them who was beautiful.`,
    `People obeyed.`,
    `The mirrors told them who was dangerous.`,
    `People nodded.`,
    `The mirrors told them who was valuable.`,
    `People competed.`,
    `The mirrors told them who was invisible.`,
    `People looked away.`,
    `And thus the oldest human hunger found its perfect instrument.`,
    `The hunger not to know oneself.`,
    `But to be known.`,
    `The distinction is everything.`,
    `One path leads inward.`,
    `The other never leaves the room.`,
    `Years later, when the mirrors finally began to fail, many celebrated.`,
    `They believed freedom had arrived.`,
    `They believed the prison walls were falling.`,
    `They believed they were witnessing liberation.`,
    `They were wrong.`,
    `The destruction of the mirrors revealed something far more terrifying.`,
    `The mirrors had never been the prison.`,
    `The mirrors had merely occupied it.`,
    `The true prison was older.`,
    `Older than governments.`,
    `Older than machines.`,
    `Older than memory itself.`,
    `It lived within the people who hated the mirrors.`,
    `Within the people who feared them.`,
    `Within the people who fought them.`,
    `Within the people who eventually destroyed them.`,
    `The mirrors shattered.`,
    `The gaze remained.`,
    `That is the story you are about to read.`,
    `Not the story of a system.`,
    `Not the story of a rebellion.`,
    `Not even the story of a people.`,
    `It is the story of an inheritance.`,
    `A gaze passed from one generation to another.`,
    `A hunger disguised as identity.`,
    `A cage rebuilt by hands that believed themselves free.`,
    `And perhaps the saddest truth of all:`,
    `The people in this story did not lose themselves because someone forced them to.`,
    `They lost themselves because they could no longer imagine who they were without being seen.`,
    `By the time they understood the difference, the mirrors had already stopped working.`,
    `And that, unfortunately, was when the real trouble began.`
  ],
};





