export const when_gods_stay_quiet_prologue = {
  slug: "when-gods-stay-quiet",
  title: "When-Gods-Stay-Quiet",
  previewStart: 0,
  previewLength: 3,
  previewCharacters: 780,
  paragraphs: [
    `Prologue`,
    `On the Matter of Silence`,
    `Few things are more misunderstood than silence. Violence is easier to grasp because cruelty leaves evidence: a broken jaw, a burned village, a body floating in a river. History has little trouble identifying the hand that strikes.`,
    `Silence is more elusive. It leaves no fingerprints, signs no confessions, and issues no commands. When the accounting begins, it often arrives disguised as innocence. After all, it did nothing—and because it did nothing, it claims responsibility for nothing. That has always been its greatest trick.`,
    `Human civilization has spent thousands of years building moral systems for judging action. We punish thieves, condemn murderers, try tyrants, build monuments to heroes, and write laws to regulate conduct. Yet when confronted with the absence of conduct, we become strangely uncertain. How should we judge the person who could have acted, but did not—the witness, the observer, the bystander, the one who remains comfortably seated while history unfolds elsewhere?`,
    `The answer, it seems, depends largely on proximity:`,
    `•	If the victim is far enough away, silence becomes prudence.`,
    `•	If the suffering is abstract enough, silence becomes neutrality.`,
    `•	If the consequences arrive slowly enough, silence becomes wisdom.`,
    `Civilizations have always been inventive in the language they use to excuse inaction. Every era develops its preferred vocabulary and mistakes those descriptions for virtues:`,
    `•	Restraint`,
    `•	Patience`,
    `•	Order`,
    `•	Decorum`,
    `•	Professionalism`,
    `•	Objectivity`,
    `•	Balance`,
    `The difficulty is that silence often looks like goodness. Good people are not usually remembered for their noise, but for their composure, patience, and ability to avoid unnecessary conflict. Parents teach it to children, churches praise it, schools reward it, and employers promote it. Entire societies are built on the assumption that calmness is evidence of character.`,
    `The lesson begins early:`,
    `•	Do not make a scene.`,
    `•	Do not draw attention.`,
    `•	Do not create trouble.`,
    `•	Do not overreact.`,
    `•	Do not disturb the peace.`,
    `By adulthood, many people have become experts in this art. They learn to recognize injustice without acknowledging it, to witness suffering without internalizing it, and to encounter cruelty while preserving the appearance of moral cleanliness. Not because they are evil, but because they are civilized. Civilization, after all, is largely the study of acceptable forms of avoidance.`,
    `This creates an uncomfortable complication. The people who commit history’s greatest crimes are relatively rare; the people who accommodate them are not. A society requires only a handful of architects to construct injustice, but it requires millions of ordinary participants to maintain it—people who consider themselves decent, reasonable, moderate, and good. They would never strike another person, yet somehow find endless reasons not to stop those who do.`,
    `History is crowded with such people. Entire centuries have been built by them. Their names are seldom remembered because they rarely stand at the center of events. Instead, they remain slightly to the side—far enough away to preserve deniability, yet close enough to benefit from the outcome.`,
    `They are not villains. Villains are easy: they simplify moral arithmetic and allow the rest of us to imagine we would have behaved differently. The truly unsettling possibility is that most injustice survives not because of villains, but because ordinary people discover convincing reasons to remain silent.`,
    `This is where the question becomes dangerous. The issue is not whether silence causes harm—it often does. Nor is it whether silence permits harm—history answers that repeatedly. The real question is whether silence itself can become a form of participation; whether neutrality, prolonged long enough, eventually chooses a side; and whether refusing responsibility is itself a decision.`,
    `Human beings prefer moral failures that arrive dramatically: a theft, a betrayal, a murder. Such failures offer emotional satisfaction because they have clear beginnings and endings. The failure of silence is different. It accumulates quietly and patiently—one ignored injustice, one overlooked cruelty, one uncomfortable truth postponed until a more convenient time.`,
    `By the time its consequences become visible, everyone involved can honestly claim they never intended the outcome, and they are usually telling the truth. Intentions are often innocent. Consequences rarely care.`,
    `Perhaps this explains humanity’s enduring fascination with gods. A god solves a very particular problem: a god sees everything, witnesses everything, knows everything. Nothing escapes divine observation. The idea reassures us because it guarantees that every injustice has at least one witness, every victim is seen, every crime is recorded, and every silence is measured. We hope the universe is paying attention.`,
    `But that reassurance contains a troubling implication. If a being possesses unlimited power, unlimited awareness, and unlimited opportunity to intervene, what moral obligations accompany such gifts? And if that being remains silent, what then?`,
    `This story concerns that question. Not the existence of power—power is common. Not the existence of evil—evil is predictable. Not even the existence of suffering—suffering requires no introduction. This story concerns witness: the burden of witness, the temptation of witness, the comfort of witness, the danger of witness, and the peculiar distance that develops when observation begins to masquerade as virtue.`,
    `Perhaps silence is innocent. Perhaps restraint is wisdom. Perhaps observation is enough. Or perhaps the oldest moral failure in the world has never been cruelty. Perhaps it has always been the decision to watch—and call it peace.`
  ],
};
