export const worldEssays = {
  "who-cleans-galts-toilets": [
  "Every revolution imagines itself as an ending. Who Cleans Galt’s Toilets? begins after that illusion has already succeeded. The Founders have won. The old world has collapsed. The most capable have withdrawn, rebuilt, prospered, and turned their refusal into civilization. For generations, the evidence appears undeniable: the revolution was right. Then history asks the question every victorious ideology hopes no one will ask: who maintains paradise?",
  "The title sounds like a joke because history often disguises its most dangerous questions as vulgarities. A shining civilization can tolerate debates about philosophy, innovation, excellence, and freedom. It is less comfortable with toilets. Toilets return every system to the body. They reveal that even the most exalted society depends on waste lines, pressure valves, filtration systems, maintenance workers, and the people whose names rarely appear on statues.",
  "Elias Vale does not hate the city. That matters. He is not a resentful outsider trying to tear down what he cannot build. He loves the city from below, from the service corridors, pressure grids, sanitation reports, and hidden infrastructure that keep its beauty functioning. His love is what makes his question so dangerous. Hatred can be dismissed. Careful observation cannot.",
  "The civilization does not call itself aristocratic. It calls itself meritocratic. It honors excellence, contribution, achievement, discipline, and earned authority. Yet Elias notices a pattern: the same families repeatedly lead, design, govern, innovate, and inherit prestige, while the same families maintain, repair, clean, stabilize, and disappear beneath the floorboards of civic glory.",
  "The horror is that the pattern is not simple fraud. There is no secret council assigning children to greatness or obscurity. The Founders’ descendants are often genuinely capable. They are educated well, mentored early, expected to lead, married into other prestigious lines, and surrounded by assumptions that polish ability into authority. Merit has not vanished. It has compounded.",
  "This is the novella’s central wound: when does merit become inheritance? The question cannot be answered by slogans. The Founders built a civilization around human variation, excellence, and unequal contribution. They were not entirely wrong. People differ. Ability differs. Discipline differs. But victory creates descendants, and descendants inherit more than genes. They inherit proximity, expectation, social permission, institutional memory, and the invisible ease of being imagined in important rooms.",
  "The maintenance class is not oppressed in the crude old sense. That is what makes the hierarchy durable. They are housed, respected, trained, praised, and needed. Their labor is called dignified. Their work sustains the high. But praise can become a polite substitute for power. Honor can be another way of asking someone not to want more.",
  "Founder Hall is the perfect temple of contradiction. Above, lectures praise the dignity of achievement beneath portraits of revolutionaries who refused to be consumed by others’ need. Below, Elias clears the waste lines behind a marble wall engraved with the principle that no man owes his life to another. The principle is real. So is the pipe. The civilization’s moral crisis begins when those two truths can no longer be kept apart.",
  "The world’s commodified element is meritocratic legitimacy. The society prices excellence, inheritance, labor, proximity, aptitude, family continuity, and the right to author the future. What is lost is not only mobility, but the ability to tell whether success still proves what the civilization says it proves. What is protected is the founding myth: that hierarchy reflects contribution rather than accumulated advantage.",
  "The Invisible Law emerges because no civilization can permanently escape human variation. Status transmits through wealth, education, mating, attention, mentorship, institutional trust, and accumulated expectation. The Founders understood difference well enough to build a revolution from it. What they failed to understand was that difference does not stop operating after victory. Especially not after victory.",
  "The marriage markets expose the mechanism nobody designed. Prestigious families increasingly intermarry. Talent concentrates with opportunity. Opportunity concentrates with reputation. Reputation concentrates with names already known. Influence does not merely pass down. It compounds until meritocracy begins to resemble aristocracy without ever formally betraying its principles.",
  "The Forgotten Founder is the ghost of the system’s own conscience. The warning was there from the beginning: a civilization built to free excellence from mediocrity might one day convert excellence into lineage. The tragedy is not betrayal alone. It is success becoming environment, environment becoming inheritance, inheritance becoming common sense.",
  "The Darwinians sharpen the danger by suggesting that hierarchy may not need institutions to create it. It may emerge from variation, selection, family formation, and time. This does not absolve the civilization. It makes responsibility harder. If hierarchy can emerge without conspiracy, then justice cannot limit itself to exposing villains. It must understand processes.",
  "The Successors arrive as every future arrives: first as an annoyance, then as a threat, then as history. They do not reject the civilization because it failed. They challenge it because it worked well enough to produce people with new questions. The old rebels become the establishment. Their descendants defend permanence with the same solemnity their ancestors once mocked.",
  "The world’s pressure point is Elias’s realization that the toilet was never the point. Nor labor. Nor sanitation. Nor even class. It was succession. Every civilization eventually creates people who inherit answers to questions they never asked, and eventually those people ask different questions. No founding philosophy can prevent this. It can only decide whether to listen before it becomes brittle.",
  "The reversal is elegant: the civilization that escaped the old order recreates an old pattern through success rather than corruption. The rebels become ancestors. The ancestors become doctrine. Doctrine becomes institution. Institution produces new rebels. History does not need enemies when it has descendants.",
  "This is why Who Cleans Galt’s Toilets? belongs in The Commodified Self. It shows the self commodified not as body, desire, memory, or perception, but as civic function. Some people inherit authorship. Others inherit usefulness. Some names become proof of excellence. Others become proof of reliability. The society praises everyone, but only some are allowed to shape what praise means.",
  "The novella’s deepest contradiction is that the civilization’s founding principle remains morally powerful even as its social reality begins to undermine it. No person may demand the unearned life of another. Yet every civilization depends on people doing the necessary work that lets others appear free, brilliant, clean, and self-made. The question is not whether such work matters. The question is who is expected to do it, whose children inherit it, and who gets to call that inheritance natural.",
  "The ending refuses collapse because collapse would be too easy. The old order gives way through transformation. The Successors become the next Founders. Students learn the old names, then the new names, then the names after them. The ideals change. The process does not. History smiles because it has heard every final answer before.",
  "In the end, the toilets were only the aperture. Through them, Elias sees the body of civilization: its waste, its dependence, its hidden labor, its inherited myths, and its failure to permanently solve history. Paradise does not fail because someone cleans its toilets. Paradise fails when it forgets that someone does."
]
} as const;

export type WorldEssaySlug = keyof typeof worldEssays;
